[package]
name = "arctonyx"
version = "0.1.0"
authors = ["Elliot Courant <me@elliotcourant.dev>"]
edition = "2018"

[dependencies]
byteorder = "1.3.2"
lazy_static = "1.4.0"
sqlparser = "0.4.0"
rocksdb = "0.12.3"
serde_json = "1.0"
